spring:
  application:
    name: login-auth-api
  datasource:
    url: jdbc:postgresql://ep-noisy-bread-a49f2z0x-pooler.us-east-1.aws.neon.tech:5432/verceldb?sslmode=require
    driver-class-name: org.postgresql.Driver
    username: default
    password: mn83xAsSPcvR
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

api:
  security:
    token:
      secret: key-3241-key

server:
  port: 8080  # Definindo a porta do servidor
